{
 "title": "PTM Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    SUM(story_points) FILTER (WHERE completion_date IS NOT NULL AND is_action)\nFROM tasks\nWHERE due_date IS NOT NULL\n  AND due_date <= (CURRENT_TIMESTAMP AT TIME ZONE 'America/Los_Angeles')\n  AND due_date >= (CURRENT_TIMESTAMP AT TIME ZONE 'America/Los_Angeles') - INTERVAL '1 days'"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    SUM(story_points) FILTER (WHERE completion_date IS NOT NULL)\nFROM tasks\nWHERE due_date IS NOT NULL\n  AND due_date <= (CURRENT_TIMESTAMP AT TIME ZONE 'America/Los_Angeles')\n  AND due_date >= (CURRENT_TIMESTAMP AT TIME ZONE 'America/Los_Angeles') - INTERVAL '1 days'"
    }
   ]
  },
  {
   "title": "Story Points",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    TO_CHAR((due_date), 'MM/DD') as due_date_str,\n    SUM(story_points) FILTER (WHERE is_action) as completed_actions,\n    SUM(story_points) FILTER (WHERE NOT is_action) as completed_tasks,\n    CASE \n        WHEN DATE(due_date) IN (\n          '2025-03-12', '2025-03-13', '2025-03-14', '2025-03-15',\n          '2025-03-16', '2025-03-23', '2025-03-31'\n        )\n        THEN 5\n        ELSE 0 \n    END AS personal_day,\n    CASE \n        WHEN DATE(due_date) IN (\n          '2025-03-24', '2025-03-29', '2025-03-30', '2025-04-06',\n          '2025-04-07'\n        ) \n        THEN 5\n        ELSE 0 \n    END AS rachna_day\nFROM tasks\nWHERE due_date IS NOT NULL\n  AND due_date <= (CURRENT_TIMESTAMP)\n  AND due_date >= (CURRENT_TIMESTAMP) - INTERVAL '30 days'\n  AND completion_date IS NOT NULL\nGROUP BY due_date\nORDER BY due_date ASC;"
    }
   ]
  },
  {
   "title": "This Week's Average Completed STPs",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 2, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(daily_story_points) AS Tasks, AVG(daily_action_tasks) AS Actions\nFROM (\n  SELECT DATE(due_date) AS due_date, SUM(story_points) AS daily_story_points, SUM(CASE WHEN is_action THEN story_points ELSE 0 END) AS daily_action_tasks\n  FROM tasks\n  WHERE due_date >= DATE_TRUNC('week', CURRENT_DATE) - INTERVAL '2 days'\n    AND due_date < CURRENT_DATE\n    AND completion_date IS NOT NULL\n    AND DATE(due_date) > '2025-04-07'\n  GROUP BY DATE(due_date)\n) AS daily_sums;"
    }
   ]
  },
  {
   "title": "Weekly Hours",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT \n    TO_CHAR(date_trunc('week', t.due_date + INTERVAL '2 days') - INTERVAL '2 days', 'MM/DD') AS week,\n    SUM(t.story_points) FILTER (WHERE t.is_action) / 4::numeric AS completed_actions,\n    SUM(t.story_points) FILTER (WHERE NOT t.is_action) / 4::numeric AS completed_tasks\nFROM tasks t\nWHERE t.due_date IS NOT NULL\n  AND t.due_date <= CURRENT_TIMESTAMP\n  AND t.due_date >= CURRENT_TIMESTAMP - INTERVAL '60 days'\n  AND t.completion_date IS NOT NULL\nGROUP BY \n    date_trunc('week', t.due_date + INTERVAL '2 days') - INTERVAL '2 days'\nORDER BY date_trunc('week', t.due_date+ INTERVAL '2 days') - INTERVAL '2 days' ASC;"
    }
   ]
  },
  {
   "title": "Weekly Avg. Story Points",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "WITH week_days AS (\n    SELECT \n        date_trunc('week', day + INTERVAL '2 days') - INTERVAL '2 days' AS week_start,\n        COUNT(*) FILTER (WHERE day::date NOT IN (\n            '2025-02-06', '2025-02-07', '2025-02-09', '2025-02-10', \n            '2025-02-11', '2025-02-15', '2025-02-17', '2025-02-21',\n            '2025-02-22', '2025-03-01', '2025-03-02', '2025-03-03',\n            '2025-03-04', '2025-03-05', '2025-03-06', '2025-03-07',\n            '2025-03-08', '2025-03-09', '2025-03-10', '2025-03-11',\n            '2025-03-12', '2025-03-13', '2025-03-14', '2025-03-15',\n            '2025-03-16', '2025-03-23', '2025-03-24', '2025-03-29',\n            '2025-03-30', '2025-03-31', '2025-04-06', '2025-04-07'\n        )) AS active_days\n    FROM generate_series(\n        CURRENT_TIMESTAMP - INTERVAL '60 days', \n        CURRENT_TIMESTAMP, \n        INTERVAL '1 day'\n    ) AS day\n    GROUP BY date_trunc('week', day + INTERVAL '2 days') - INTERVAL '2 days'\n)\nSELECT \n    TO_CHAR(date_trunc('week', t.due_date + INTERVAL '2 days') - INTERVAL '2 days', 'MM/DD') AS week,\n    SUM(t.story_points) FILTER (WHERE t.is_action) / w.active_days::numeric AS completed_actions,\n    SUM(t.story_points) FILTER (WHERE NOT t.is_action) / w.active_days::numeric AS completed_tasks\nFROM tasks t\nJOIN week_days w ON date_trunc('week', t.due_date + INTERVAL '2 days') - INTERVAL '2 days' = w.week_start\nWHERE t.due_date IS NOT NULL\n  AND t.due_date <= CURRENT_TIMESTAMP\n  AND t.due_date >= CURRENT_TIMESTAMP - INTERVAL '60 days'\n  AND DATE(t.due_date) NOT IN (\n    '2025-02-06', '2025-02-07', '2025-02-09', '2025-02-10', \n    '2025-02-11', '2025-02-15', '2025-02-17', '2025-02-21',\n    '2025-02-22', '2025-03-01', '2025-03-02', '2025-03-03',\n    '2025-03-04', '2025-03-05', '2025-03-06', '2025-03-07',\n    '2025-03-08', '2025-03-09', '2025-03-10', '2025-03-11',\n    '2025-03-12', '2025-03-13', '2025-03-14', '2025-03-15',\n    '2025-03-16', '2025-03-23', '2025-03-24', '2025-03-29',\n    '2025-03-30', '2025-03-31', '2025-04-06', '2025-04-07'\n  )\n  AND t.completion_date IS NOT NULL\nGROUP BY \n    date_trunc('week', t.due_date + INTERVAL '2 days') - INTERVAL '2 days',\n    w.active_days\nORDER BY date_trunc('week', t.due_date + INTERVAL '2 days') - INTERVAL '2 days' ASC;"
    }
   ]
  },
  {
   "title": "THIS WEEK'S GOALS (MAX. 5)",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT \n    name AS goal, \n    (completion_date IS NOT NULL) AS is_complete, \n    ancestors AS context \nFROM tasks \nWHERE (is_week_goal = true \n  AND due_date >= date_trunc('week', CURRENT_DATE) - INTERVAL '2 days'\n  AND due_date < date_trunc('week', CURRENT_DATE) - INTERVAL '2 days' + INTERVAL '1 week') \nORDER BY (completion_date IS NOT NULL) ASC, reverse(ancestors) \nLIMIT 50"
    }
   ]
  },
  {
   "title": "THIS MONTH'S GOALS",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT name as goal, (completion_date IS NOT NULL) as is_complete, ancestors as context FROM tasks WHERE (is_month_goal = true AND due_date >= date_trunc('month', CURRENT_DATE)\n  AND due_date < date_trunc('month', CURRENT_DATE) + INTERVAL '1 month') ORDER BY (completion_date IS NOT NULL) ASC, reverse(ancestors) LIMIT 50"
    }
   ]
  },
  {
   "title": "THIS QUARTER'S GOALS",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT name as goal, (completion_date IS NOT NULL) as is_complete, ancestors as context FROM tasks WHERE (is_quarter_goal = true AND due_date >= date_trunc('quarter', CURRENT_DATE)\n  AND due_date < date_trunc('quarter', CURRENT_DATE) + INTERVAL '3 months') ORDER BY (completion_date IS NOT NULL) ASC, reverse(ancestors) LIMIT 50"
    }
   ]
  },
  {
   "title": "ON DECK",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT name as task, ancestors as context FROM tasks WHERE (is_ondeck = true AND completion_date IS NULL)\n  ORDER BY reverse(ancestors) LIMIT 50"
    }
   ]
  },
  {
   "title": "Goal Completions (Weekly)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT \n    TO_CHAR(DATE_TRUNC('week', due_date) - INTERVAL '2 days', 'MM/DD') as week_start,\n    COUNT(*) FILTER (WHERE completion_date IS NOT NULL) as completed,\n    COUNT(*) FILTER (WHERE completion_date IS NULL) as pending\nFROM tasks\nWHERE due_date IS NOT NULL\n  AND due_date <= (CURRENT_TIMESTAMP)\n  AND due_date >= (CURRENT_TIMESTAMP) - INTERVAL '180 days'\n  AND (is_week_goal OR is_month_goal OR is_quarter_goal OR is_annual_goal)\nGROUP BY DATE_TRUNC('week', due_date) - INTERVAL '2 days'\nORDER BY DATE_TRUNC('week', due_date) - INTERVAL '2 days' ASC;"
    }
   ]
  },
  {
   "title": "Goal Completions (Monthly)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT \n    TO_CHAR(DATE_TRUNC('month', due_date), 'MM') as month_start,\n    COUNT(*) FILTER (WHERE completion_date IS NOT NULL) as completed,\n    COUNT(*) FILTER (WHERE completion_date IS NULL) as pending\nFROM tasks\nWHERE due_date IS NOT NULL\n  AND due_date <= (CURRENT_TIMESTAMP)\n  AND due_date >= (CURRENT_TIMESTAMP) - INTERVAL '360 days'\n  AND (is_week_goal OR is_month_goal OR is_quarter_goal OR is_annual_goal)\nGROUP BY DATE_TRUNC('month', due_date)\nORDER BY DATE_TRUNC('month', due_date) ASC;"
    }
   ]
  }
 ]
}